---
- hosts: all
  become: yes
  vars:
    ansible:
      galaxy:
        roles:
          - geerlingguy.docker
    docker_users:
      - vagrant
  tasks:
    - name: Install ansible galaxy roles
      command: "ansible-galaxy install {{ item }} -p /etc/ansible/roles/"
      loop: "{{ ansible.galaxy.roles }}"

    - name: Install docker
      include_role:
        name: geerlingguy.docker

    - name: Download minio
      get_url:
        url: https://dl.min.io/server/minio/release/linux-amd64/minio
        dest: /usr/local/bin/minio
        mode: 'a+x'

    - name: Download minio client (mc)
      get_url:
        url: https://dl.min.io/client/mc/release/linux-amd64/mc
        dest: /usr/local/bin/mc
        mode: 'a+x'

    - name: Install systemd unit file minio
      template: src=minio.service.j2 dest=/etc/systemd/system/minio.service
